pluginManagement {
    repositories {
        maven { url 'https://maven-central.storage-download.googleapis.com/maven2/' }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
include ':app'
